//">"横着移动得火焰
/***************************************************************************
 *        图例
 *    x         云梯
 *    r         暗河
 *    @         玩家
 *    e         怪物
 *    !         不会移动的火焰         
 *    =         横向来回移动的火焰
 *    |         垂直来回移动的火焰
 *    v         不断下落的火焰
 *    b         射出的子弹（不能在地图中出现，由玩家执行shoot命令后自动生成）
 *    #         目标
 *    =         灵光球
 ****************************************************************************/

var GAME_LEVELS = [
  [
    "                                                         ",
    "  x                                                    x  ",
    "  x                                                    x  ",
    "  x       xx                 xx                        x  ",
    "  x      x  x               x  x                       x  ",
    "  x      x   x             x   x                       x  ",
    "  x      x    xxxxxxxxxxxxx    x                       x  ",
    "  x      x                     x                   x   x  ",
    "  x      x                     x                  xxx  x  ",
    "  x     x xxxxxx       xxxxx    x                x   x x  ",
    "  x     xx     xx     x    xx   x               x     xx  ",
    "  x     xx    xxx     x   xxx   x                      x  ",
    "  x     x xxxxxx       xxxxx    x                      x  ",
    "  x     x                       x                      x  ",
    "  x     x                       x                x # x x  ",
    "  x      x        xxx           x               xxxxxxxx  ",
    "  x      x        xxx          x               xxxxxxxxx  ",
    "  x       xx       x    x    xx               xxxxxxxxxx  ",
    "  x         x      x   x    x                xxxxxxxxxxx  ",
    "  x         x   xxxxxxx    x                xxxxxxxxxxxx  ",
    "  x          x            xx               xxxxxxxxxxxxx  ",
    "  x           xxxxxxxxxxxx      xxxx      xxxxxxxxxxxxxx  ",
    "  x                                      xxxxxxxxxxxxxxx  ",
    "  x      v                              xxxxxxxxxxxxxxxx  ",
    "  x                                    xxxxxxxxxxxxxxxxx  ",
    "  x @                                 xxxxxxxxxxxxxxxxxx  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                          "],
  ["                                                                 ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                  xxx           ",
    "       x                                         xx!xx          ",
    "        x                                        x!!!x          ",
    "  xxxxxxxx                                       xx!xx          ",
    "  x     x                                         xvx           ",
    "  x    x                                                    xx  ",
    "  x                               o                          x  ",
    "  x                                                          x  ",
    "  x              o                                         # x  ",
    "  x                                                          x  ",
    "  x @    x       x        x                     xxxxx        x  ",
    "  xxxxxxxxrrrrrrrrrrrrrrrrxxxxx       xxxxxxxxxxx   xxxxxxxxxx  ",
    "         xrrrrrrrrrrrrrrrrx   x       x                         ",
    "          xxxxrrrrrrrrrrxx    xrrrrrrrx                         ",
    "              xrrrrrrxxx      xrrrrrrrx                         ",
    "               xxxxxx         xxxxxxxxx                         ",
    "                                                                                ",
    "                                                                                "],
  ["                 xxx                                                 ",
    "                  xxxrrrx                                             ",
    "                     xrx                                           #  ",
    "                      x                                            x  ",
    "                                                                      ",
    "  @                                                      o            ",
    "xxxxxxxxxxxx                                    xe       x            ",
    "rrrrrrrrr xxx                                  xxxxxxxxxxxx        x  ",
    "rrrrxxxxr  xxx                                xxx                     ",
    "rrrrrxx r   xxxxxxxxx=                   =xxxxxx                      ",
    "rrrxxx  v                                                             ",
    "xxxx                                                                  ",
    "xxxo                             xxx                =x                ",
    "xo             ooooo              xxx                                 ",
    "              xxxxxxx              xxxxxx                             ",
    "                                                     o     rrrrrrrrrrr",
    "                                                    ooo    rxrrrrrrrrr",
    "e        ex                                    xxxxxxxxx   r xrrrrrrrr",
    "xxxxxxxxxxx                                   xxx          r  xrrrrrrr",
    "                                             xxx           r   xrrrrrr",
    "               ooooo                        xxx            r    xrrrrr",
    "              xxxxxxx=               xxxxxxxxx             r     xxrrr",
    "                                                           r      xxrr",
    "                             x                             r       xxx",
    "                                                           r        xx"],


  ["                                                                                                                         ",
    "                                                                                                                         ",
    "                                                                                                                         ",
    "                                                                                                                         ",
    "                                                                                                                         ",
    "                                                                                                      x          o       ",
    "                                             xe       x=         x                                    v        # x       ",
    "  oo                                        xxxxxxxxxxx          xxxx                                          rrxo      ",
    "oooooo                                     xx              xx       xx       xe    x                    o     rrxxx      ",
    "  oo                                      xx        rr               xxx     xxxxxxx    xx              x    rrxxx       ",
    "                               xxxxxxxxxxxx          rr   |rrr                          xx=                =rrxxxx       ",
    "                                                  rrr  rrrr   r                         xx                 rrxxxxx      o",
    "e           exe          ex                    rrrrrrr   rr    r                        xx        o       rrxxxxxx      x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxx                    rr   rrrr rr                             xx        x      rrxxxxxxx       ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           v      rrrrrr rrr                        xx             rrrrxxxxxxx       ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           rrrrrrrrrr  r                         xxrrrrrrrrrrrrrrrxxxxxxxxxo      ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       rrr  rrrrrr                            xxxxxxxxxxxxxxrrxxxxxxxxxxx      ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     r    rrrrr                                          rr                 ",
    "                       v                          v     rrr                                           rr           o     ",
    "                                                        rrr                                           rr           x     ",
    "       x         o                             x     x  rrr                                        rrrrrrrrrrrrrrrrx     ",
    "    o   x                                      x     x  rrr                                        vxxxxxxxxxxxxxxxx    o",
    " xxxxxxxxx=          =     x    =             =x     x  rrr                                        v        o           x",
    "        x                                      x     x  rrr                                                ooo           ",
    "       x                                       xx    x  rrr                                              ooooooo         ",
    "             x                                 x     x  rrr                                            xxxxxxxxxxxxx     ",
    "                       x            xxx        x     x  rrr                                                              ",
    "                       x        x   x=         x     x  rrr                                                              ",
    "                       x        x o x          x    xx  rrr                                  xxxxx                       ",
    "     @             x   x        x   x     o    x     x  rrr                                 xx                           ",
    "    xxx      x         x        x   x     x    x     x  rrr                             o    x                           ",
    "    x x      xrrrrrrrrrx       xx o xx         x     x  rrr                o     x x    o    x                           ",
    "rrrrx xrrrrrrxrrrrrrrrrxrrrrrrxx     xxrrrrrrrxxx    xrrrrrrrrrr     xe          x x    o    x                           ",
    "rrrrx xrrrrrrxrrrrrrrrrxrrrrrxx       xxxxxxxxxx     xrrrrrrrxxr      xxxxxxxxxxxx xx  o o  xx                           ",
    "rrrrx xrrrrrrxrrrrrrrrrxrrrrrx    o                 xxrrrrrrxx r                    xxoooooxx                            ",
    "rrrrx xrrrrrrxrrrrrrrrrxrrrrrx                     xxrrrrrrxx  r                     xxxxxxx                             ",
    "rrrrx xrrrrrrxrrrrrrrrrxrrrrrxx     xxxxxxxxxxxxxxxxrrrrrrxx   r                                                         ",],
  ["                                                                                        ooo                 x ",
    "                                                                                      ooooooo             x x ",
    "                                                                                        ooo                xx ",
    "                                                                                                            x ",
    "                                                                              xe         e         ex         ",
    "                                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
    "                                                                         xxrrrrrrrrrrrrrrrrrrrrrrrrrrrrx      ",
    "xxxxxxxxxxxxxxxxxxxxxxxx                                               xxrrrrxrrrrrrxrrrrrrxrrrrrrxrrrrrx     ",
    "                                                                     xxrrrrrxxxrrrrxxxrrrrxxxrrrrxxxrrrx      ",
    "                                                                   xx  xxrrrrxrrrrrrxrrrrrrxrrrrrrxrrrx       ",
    "oooo                                                             xx      xxrrrrrrrrrrrrrrrrrrrrrrrrrxx        ",
    "oooo                                                                       xxxrxxxrrrrrrrrrrrrrrrrrx          ",
    "oooo                                                                          v   xxxrxxxrrrrrrrrrrx          ",
    "oooo       x                   xxxxx                         x         =x            v   xxrrrrrrxx           ",
    "           x                     xxxx                                                      xrxrxx             ",
    "e         ex                       xxx                                                      x r               ",
    "xxxxxxxxxxxx||xxxxxxxxxx            =xx                                                       r               ",
    "rrrrrrrrrrrrrrrrrrrrrrrrxx             x                           x         =x               r               ",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrxx            x                                                     v               ",
    "rrrrrrrrrrrrrrxxxxrrrrrrrrrrxx          =x                                                                    ",
    "xxxxxxxxxxxrrrrx xxrrrrxxrrrrrxx          x                               x       x  x                        ",
    "          xrrrx   xxxrxxxxrrrrrrxx         x                                                                  ",
    "           xrrx      v   xxxxxxrrrxx       xx                                                                 ",
    "       x    xrrx          x    xxrrrx      xxxxxxxxx                                                          ",
    "      xrx    xrx                 xxx       xx      xx                                     x   xr              ",
    "xxxxxxxxrx    v                            xx       xx                                                        ",
    "rrrrrrrrrrx                               oxx        xx                                                       ",
    "rrrxxxxxxvx                oo             xxx         xx                                                      ",
    "rrr                      xxxxxx=          =xx          xxxxxxxxx=              x=             x              # ",
    "rrr              o       xxxxxx                         x                                            rrrrrrrrr",
    "rrr              x       x                  rrrrrrrrrrrrx                                            rxrrrrrrr",
    "rrr       o      x       x  o        x      rxrrrrrrrrrrx                                            r xrrrrrr",
    "rrr   @   o      xrrrrrrrx ooo              r xrrrrrrrrrx                x              x            r  xxxxxx",
    "rrrxxxxxxxx      xrrrrrrrxooooo             r  xrrrrrrrrxxxrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrxxxxx",
    "rrrxxxxxxxxrrrrrrxrrrrrrrxxxxxxx            rx  xxxxrrrrxxxxrrrrrrrrrrrrrrrrrrxxxxrrrrrrrrrrrrrrrrrrrrrxxxxxxx",
    "rrrxxxxxxxxrrrrrrxrrrrrrrxxxxxxxxrrrrrrrrrrrrrx     xrrrxxxxxrrrrrrrrrrrrrrrrxxxxxxrrrrrrrrrrrrrrrrrrxxxxxxxxx",
    "rrrxxxxxxxxrrrrrrxrrrrrrrxxxxxxxxxrrrrrrrrrrrx      xrrrxxxrrrrrrrrrrrrrrrrrxxxxxxxxrrrrrrrrrrrrrrrrxxxxxxxxxx"]
];
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;

GAME_LEVELS.forEach(function (level) {
  level.forEach(function (row) {
    row.split("").forEach(function (ele) {
      if (ele == "o") gameData.tot_allCoinNums++;
      if (ele == "e") gameData.tot_allEnemyNums++;
    });
  });
});