//">"横着移动得火焰
/***************************************************************************
 *        图例
 *    x         云梯
 *    r         暗河
 *    @         玩家
 *    e         怪物
 *    !         不会移动的火焰         
 *    =         横向来回移动的火焰
 *    |         垂直来回移动的火焰
 *    v         不断下落的火焰
 *    b         射出的子弹（不能在地图中出现，由玩家执行shoot命令后自动生成）
 *    #         目标
 *    =         灵光球
 ****************************************************************************/



var GAME_LEVELS = [
  [
    "                                                         ",
    "  x                                                    x  ",
    "  x                                                    x  ",
    "  x       xx                 xx                        x  ",
    "  x      x  x               x  x                       x  ",
    "  x      x   x             x   x                       x  ",
    "  x      x    xxxxxxxxxxxxx    x                       x  ",
    "  x      x                     x                   x   x  ",
    "  x      x                     x                  xxx  x  ",
    "  x     x xxxxxx       xxxxx    x                x   x x  ",
    "  x     xx     xx     x    xx   x               x     xx  ",
    "  x     xx    xxx     x   xxx   x                      x  ",
    "  x     x xxxxxx       xxxxx    x                      x  ",
    "  x     x                       x                      x  ",
    "  x     x                       x                x # x x  ",
    "  x      x        xxx           x               xxxxxxxx  ",
    "  x      x        xxx          x               xxxxxxxxx  ",
    "  x       xx       x    x    xx               xxxxxxxxxx  ",
    "  x         x      x   x    x                xxxxxxxxxxx  ",
    "  x         x   xxxxxxx    x                xxxxxxxxxxxx  ",
    "  x          x            xx               xxxxxxxxxxxxx  ",
    "  x           xxxxxxxxxxxx      xxxx      xxxxxxxxxxxxxx  ",
    "  x                                      xxxxxxxxxxxxxxx  ",
    "  x                                     xxxxxxxxxxxxxxxx  ",
    "  x                                    xxxxxxxxxxxxxxxxx  ",
    "  x @                                 xxxxxxxxxxxxxxxxxx  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                      ",
  ],
  ["                                                                 ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "                                                  xxx           ",
    "       x                                         xx!xx          ",
    "        x                                        x!!!x          ",
    "  xxxxxxxx                                       xx!xx          ",
    "  x     x                                         xvx           ",
    "  x    x                                                    xx  ",
    "  x                               o                          x  ",
    "  x                                                          x  ",
    "  x              o                                         # x  ",
    "  x                                                          x  ",
    "  x@     x       x        x                     xxxxx        x  ",
    "  xxxxxxxxrrrrrrrrrrrrrrrrxxxxx       xxxxxxxxxxx   xxxxxxxxxx  ",
    "         xrrrrrrrrrrrrrrrrx   x       x                         ",
    "          xxxxrrrrrrrrrrxx    xrrrrrrrx                         ",
    "              xrrrrrrxxx      xrrrrrrrx                         ",
    "               xxxxxx         xxxxxxxxx                         ",
    "                                                                ",
    "                                                                "],

  ["                                                                                                                         ",
    "                                                                                                                         ",
    "                                                                                                                         ",
    "                                                                                                                         ",
    "                                                                                                                         ",
    "                                                                                                      x          o       ",
    "                                                                                                      v        # x       ",
    "                                            xxxxxxxxxxx          xxxx                                          rrxo      ",
    "                                           xx              xx       xx                                  o     rrxxx      ",
    "                                          xx        rr               xxx     xxxxxxx    xx              x    rrxxx       ",
    "                               xxxxxxxxxxxx          rr   |rrr                          xx=                =rrxxxx       ",
    "                                                  rrr  rrrr   r                         xx                 rrxxxxx      o",
    "                                               rrrrrrr   rr    r                        xx        o       rrxxxxxx      x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxx                    rr   rrrr rr                             xx        x      rrxxxxxxx       ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           v      rrrrrr rrr                        xx             rrrrxxxxxxx       ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           rrrrrrrrrr  r                         xxrrrrrrrrrrrrrrrxxxxxxxxxo      ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       rrr  rrrrrr                            xxxxxxxxxxxxxxrrxxxxxxxxxxx      ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     r    rrrrr                                          rr                 ",
    "                       v                          v     rrr                                           rr           o     ",
    "                                                        rrr                                           rr           x     ",
    "       x         o                             x     x  rrr                                        rrrrrrrrrrrrrrrrx     ",
    "    o   x                                      x     x  rrr                                        vxxxxxxxxxxxxxxxx    o",
    " xxxxxxxxx=          =     x    =             =x     x  rrr                                                 o           x",
    "        x                                      x     x  rrr                                                ooo           ",
    "       x                                       xx    x  rrr                                              ooooooo         ",
    "             x                                 x     x  rrr                                            xxxxxxxxxxxxx     ",
    "                       x            xxx        x     x  rrr                                                              ",
    "                       x        x   x          x     x  rrr                                                              ",
    "                       x        x o x          x    xx  rrr                                  xxxx                        ",
    "     @             x   x        x   x     o    x     x  rrr                                 xx                           ",
    "    xxx      x         x        x   x     x    x     x  rrr                             o    x                           ",
    "    x x      x         x       xx o xx         x     x  rrr                o     x x    o    x                           ",
    "rrrrx xrrrrrrx         xrrrrrrxx     xxrrrrrrrxxx    xrrrrrrrrrr                 x x    o    x                           ",
    "rrrrx xrrrrrrx         xrrrrrxx       xxxxxxxxxx     xrrrrrrrxxr      xxxxxxxxxxxx xx  o o  xx                           ",
    "rrrrx xrrrrrrx         xrrrrrx    o                 xxrrrrrrxx r rrrrrrrrrrrrrrrrrrrxxoooooxx                            ",
    "rrrrx xrrrrrrx         xrrrrrx                     xxrrrrrrxx  rrrrrrrrrrrrrrrrrrrrrrxxxxxxx                             ",
    "rrrrx xrrrrrrx         xrrrrrxx     xxxxxxxxxxxxxxxxrrrrrrxx   rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",],
  ["                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                        o                                                                     ",
    "                                                                                                              ",
    "                                        x                                                                     ",
    "                                        x                                                                     ",
    "                                        x                                                                     ",
    "                                        x                                                                     ",
    "                                       xxx                                                                    ",
    "                                       x x                 !!!        !!!  xxx                                ",
    "                                       x x                 !x!        !x!                                     ",
    "                                     xxx xxx                x          x                                      ",
    "                                      x   x                 x   #ooo   x       xxx                            ",
    "                                      x   x                 x          x      x!!!x                           ",
    "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
    "                                     xx   xx      x   x      x                                                ",
    "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
    "                                      x   x           x                    x!!!x                              ",
    "                                      x   x           x                     xxx                               ",
    "                                     xx   xx          x                                                       ",
    "                                      x   x= = = =    x            xxx                                        ",
    "                                      x   x           x           x!!!x                                       ",
    "                                      x   x    = = = =x     o      xxx       xxx                              ",
    "                                     xx   xx          x                     x!!!x                             ",
    "                              o   o   x   x           x     x                xxv        xxx                   ",
    "                                      x   x           x              x                 x!!!x                  ",
    "                             xxx xxx xxx xxx     o o  xrrrrrrrrrrrrrrx                   vx                   ",
    "                             x xxx x x xxx x          xrrrrrrrrrrrrrrx                                        ",
    "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
    "                             xx           xx                                         xxx                      ",
    "  xxx                         x     x     x                                         x!!!x                xxx  ",
    "  x x                         x    xxx    x                                          xxx                 x x  ",
    "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
    "  x                           x           x                              x   x                             x  ",
    "  x                           xx          x                              x x x                             x  ",
    "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
    "  x                xxx             o o    x                              x         xxx                     x  ",
    "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
    "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
    "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
    "  x      @          x         x           xrrx    xrrrrx    xrrrrx    xx   xx                    x         x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "                                                                                                              ",
    "                                                                                                              "],
  ["                                                                                                  xxx x       ",
    "                                                                                                      x       ",
    "                                                                                                  xxxxx       ",
    "                                                                                                  x           ",
    "                                                                                                  x xxx       ",
    "                          o                                                                       x x x       ",
    "                                                                                             o # oxxx x       ",
    "                   xxx                                                                                x       ",
    "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
    "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
    "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
    "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
    "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
    "                                                                                                              ",
    "          o              xxx                              xx                                                  ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                      xx                                                      ",
    "                   xxx         xxx                                                                            ",
    "                                                                                                              ",
    "                          o                                                     x      x                      ",
    "                                                          xx     xx                                           ",
    "             xxx         xxx         xxx                                 x                  x                 ",
    "                                                                                                              ",
    "                                                                 ||                                           ",
    "  xxxxxxxxxxx                                                                                                 ",
    "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
    "  x         x   x       x   x       x   x                 ||                  x     x                         ",
    "  x@        xxxxx   o   xxxxx   o   xxxxx                                                                     ",
    "  xxxxxxx                                     xxxxx       xxx     xx     xxx                                  ",
    "        x=                  =                =x   x                     xxx                                   ",
    "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xrrrrrrrrrrrrrrrrrrrrrxxxrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;

GAME_LEVELS.forEach(function (level) {
  level.forEach(function (row) {
    row.split("").forEach(function (ele) {
      if (ele == "o") gameData.tot_allCoinNums++;
      if (ele == "e") gameData.tot_allEnemyNums++;
    });
  });
});